#pragma once

struct EditorState;

enum EDITOR_INPUT_MAPPING : unsigned char {
	EDITOR_INPUT_NEW_PROJECT,
	EDITOR_INPUT_OPEN_PROJECT,
	EDITOR_INPUT_SAVE_PROJECT,
	EDITOR_INPUT_TRANSLATION_TOOL,
	EDITOR_INPUT_ROTATION_TOOL,
	EDITOR_INPUT_SCALE_TOOL,
	EDITOR_INPUT_MAPPING_COUNT
};

void InitializeInputMapping(EditorState* editor_state);