#pragma once

#define EDITOR_GREEN_COLOR Color(30, 140, 70)
#define EDITOR_RED_COLOR Color(160, 40, 30)
#define EDITOR_YELLOW_COLOR Color(180, 180, 60)
#define EDITOR_SELECT_COLOR EDITOR_GREEN_COLOR
#define EDITOR_DEEP_BLUE_COLOR Color(20, 20, 100)

#define EDITOR_STATISTIC_CPU_USAGE_COLOR Color(0, 128, 192)
#define EDITOR_STATISTIC_RAM_USAGE_COLOR EDITOR_STATISTIC_CPU_USAGE_COLOR
#define EDITOR_STATISTIC_GPU_USAGE_COLOR Color(0, 128, 64)
#define EDITOR_STATISTIC_VRAM_USAGE_COLOR EDITOR_STATISTIC_GPU_USAGE_COLOR
#define EDITOR_STATISTIC_SANDBOX_TIME_COLOR Color(192, 128, 128)
#define EDITOR_STATISTIC_FRAME_TIME_COLOR EDITOR_STATISTIC_SANDBOX_TIME_COLOR
#define EDITOR_STATISTIC_GPU_TIME_COLOR EDITOR_STATISTIC_SANDBOX_TIME_COLOR
#define EDITOR_STATISTIC_TEXT_COLOR Color(255, 128, 0)