#include "editorpch.h"
#include "ModuleDefinition.h"

ECSEngine::Stream<wchar_t> MODULE_ASSOCIATED_FILES[] = {
	L".dll",
	L".pdb",
	L".lib",
	L".exp"
};

size_t MODULE_ASSOCIATED_FILES_SIZE() {
	return std::size(MODULE_ASSOCIATED_FILES);
}

ECSEngine::Stream<char> MODULE_CONFIGURATIONS[] = {
	MODULE_CONFIGURATION_DEBUG,
	MODULE_CONFIGURATION_RELEASE,
	MODULE_CONFIGURATION_DISTRIBUTION
};

ECSEngine::Stream<wchar_t> MODULE_CONFIGURATIONS_WIDE[] = {
	MODULE_CONFIGURATION_DEBUG_WIDE,
	MODULE_CONFIGURATION_RELEASE_WIDE,
	MODULE_CONFIGURATION_DISTRIBUTION_WIDE
};