#pragma once

#include "../ECSEngine/Utilities/Assert.h"
#include "../ECSEngine/Utilities/BasicTypes.h"
#include "../ECSEngine/Utilities/StringUtilities.h"
#include "../ECSEngine/Utilities/StreamUtilities.h"
#include "../ECSEngine/Utilities/FilePreprocessor.h"
#include "../ECSEngine/Utilities/Utilities.h"
#include "../ECSEngine/Utilities/PointerUtilities.h"
#include "../ECSEngine/Utilities/ParsingUtilities.h"
#include "../ECSEngine/Utilities/Algorithms.h"
#include "../ECSEngine/Utilities/Timer.h"
#include "../ECSEngine/Utilities/Path.h"
#include "../ECSEngine/Utilities/File.h"
#include "../ECSEngine/Utilities/ForEachFiles.h"
#include "../ECSEngine/Utilities/Crash.h"
#include "../ECSEngine/Utilities/Tokenize.h"

#include "../ECSEngine/Utilities/Encryption.h"
#include "../ECSEngine/Utilities/FilePackaging.h"
#include "../ECSEngine/Utilities/BufferedFileReaderWriter.h"
#include "../ECSEngine/Utilities/InMemoryReaderWriter.h"

#include "ECSEngineReflection.h"
#include "ECSEngineSerialization.h"